In [1]:
import pandas  as  pd

In [2]:
df = pd.read_csv(r"C:\Users\admin\Downloads\hitters (1).csv")

# basic check

In [3]:
df.head()

,Name,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,...,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
0,Andy Allanson,293,66,1,30,29,14,1,293,66,...,30,29,14,A,E,446,33,20,NaN,A
1,Alan Ashby,315,81,7,24,38,39,14,3449,835,...,321,414,375,N,W,632,43,10,475.0,N
2,Alvin Davis,479,130,18,66,72,76,3,1624,457,...,224,266,263,A,W,880,82,14,480.0,A
3,Andre Dawson,496,141,20,65,78,37,11,5628,1575,...,828,838,354,N,E,200,11,3,500.0,N
4,Andres Galarraga,321,87,10,39,42,30,2,396,101,...,48,46,33,N,E,805,40,4,91.5,N

In [4]:
df.columns

Index(['Name', 'AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years',
       'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CRBI', 'CWalks', 'League',
       'Division', 'PutOuts', 'Assists', 'Errors', 'Salary', 'NewLeague'],
      dtype='object')

In [6]:
df.isnull().sum()

Name          0
AtBat         0
Hits          0
HmRun         0
Runs          0
RBI           0
Walks         0
Years         0
CAtBat        0
CHits         0
CHmRun        0
CRuns         0
CRBI          0
CWalks        0
League        0
Division      0
PutOuts       0
Assists       0
Errors        0
Salary       59
NewLeague     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
# Hitters Dataset
# ------------------
# Find out no of missing values in each column





# -------------
# Cars Dataset
# -------------


# 1. Find out car having highest Mileage in city
# 2. Find out Models of cars which are having Price between 17 and 25
# 3. Find out top 7 most fuel economic cars for highway

# 5. Find out top 7 most fuel economic cars for city, show results in sorted manner based on Horsepower.

In [9]:
# ------------------
# Find out no of missing values in each column
df.isna().sum()

Name          0
AtBat         0
Hits          0
HmRun         0
Runs          0
RBI           0
Walks         0
Years         0
CAtBat        0
CHits         0
CHmRun        0
CRuns         0
CRBI          0
CWalks        0
League        0
Division      0
PutOuts       0
Assists       0
Errors        0
Salary       59
NewLeague     0
dtype: int64

In [10]:
df.columns

Index(['Name', 'AtBat', 'Hits', 'HmRun', 'Runs', 'RBI', 'Walks', 'Years',
       'CAtBat', 'CHits', 'CHmRun', 'CRuns', 'CRBI', 'CWalks', 'League',
       'Division', 'PutOuts', 'Assists', 'Errors', 'Salary', 'NewLeague'],
      dtype='object')

In [11]:
# Find of people who have batted for more than 400 matches
df.query('CAtBat>400')[['Name',  'CAtBat' ]]
df[df['CAtBat']>400][['Name',  'CAtBat' ]]

                Name  CAtBat
1         Alan Ashby    3449
2        Alvin Davis    1624
3       Andre Dawson    5628
5    Alfredo Griffin    4408
7    Argenis Salazar     509
..               ...     ...
317     Willie McGee    2703
318  Willie Randolph    5511
319   Wayne Tolleson    1700
320    Willie Upshaw    3198
321    Willie Wilson    4908

[284 rows x 2 columns]

In [12]:
# Find out the name of the player who has hit max home runs
df.sort_values(by  ='CHmRun' ,  ascending  = False)[['Name' , 'CHmRun']].head(1)

               Name  CHmRun
249  Reggie Jackson     548

In [14]:
df.CHmRun.max()

548

In [15]:
df[df['CHmRun']==548]

,Name,AtBat,Hits,HmRun,Runs,RBI,Walks,Years,CAtBat,CHits,...,CRuns,CRBI,CWalks,League,Division,PutOuts,Assists,Errors,Salary,NewLeague
249,Reggie Jackson,419,101,18,65,58,92,20,9528,2510,...,1509,1659,1342,A,W,0,0,0,487.5,A

In [16]:
# Find out league wise total number of players
df.League.value_counts()
df.groupby('League').Name.count()

League
A    175
N    147
Name: Name, dtype: int64

In [17]:
# Find out division wise total amount of salary invested
df.groupby('Division').Salary.sum()

Division
E    80531.006
W    60417.501
Name: Salary, dtype: float64

In [20]:
# Find out five most senior players.
df.sort_values('Years'  , ascending  = False).head(5)[['Name' ,  'Years']]

               Name  Years
236       Pete Rose     24
302      Tony Perez     23
121   Graig Nettles     20
249  Reggie Jackson     20
306     Ted Simmons     19

# Cars

In [21]:
df = pd.read_csv(r"C:\Users\admin\Downloads\Cars93 (2).csv")

In [22]:
df.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

In [24]:
df.columns

Index(['id', 'Manufacturer', 'Model', 'Type', 'Min.Price', 'Price',
       'Max.Price', 'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain',
       'Cylinders', 'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile',
       'Man.trans.avail', 'Fuel.tank.capacity', 'Passengers', 'Length',
       'Wheelbase', 'Width', 'Turn.circle', 'Rear.seat.room', 'Luggage.room',
       'Weight', 'Origin', 'Make'],
      dtype='object')

In [27]:
# 1. Find out car having highest Mileage in city
df.sort_values(by  ='MPG.city' ,  ascending  = False).head(1)
df['MPG.city'].max()
df.query('`MPG.city`==46')

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,NaN,...,4,151,93,63,34,27.5,10.0,1695,non-USA,Geo Metro

In [28]:
 #2. Find out Models of cars which are having Price between 17 and 25
 df[df['Price'].between(17 ,25 )]

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,19,28,Driver only,...,6,200,111,74,42,30.5,17.0,3470,USA,Buick LeSabre
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,6,216,116,78,45,30.5,21.0,4105,USA,Buick Roadmaster
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver & Passenger,...,6,203,113,74,40,31.0,15.0,3515,USA,Chrylser Concorde
25,26,Dodge,Caravan,Van,13.6,19.0,24.4,17,21,Driver only,...,7,175,112,72,42,26.5,NaN,3705,USA,Dodge Caravan
29,30,Eagle,Vision,Large,17.5,19.3,21.2,20,28,Driver & Passenger,...,6,202,113,74,40,30.0,15.0,3490,USA,Eagle Vision
35,36,Ford,Aerostar,Van,14.5,19.9,25.3,15,20,Driver only,...,7,176,119,72,45,30.0,NaN,3735,USA,Ford Aerostar
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,27.5,18.0,3325,USA,Ford Taurus
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,6,212,114,78,43,30.0,21.0,3950,USA,Ford Crown_Victoria
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver & Passenger,...,4,175,100,70,39,23.5,8.0,2865,non-USA,Honda Prelude
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver & Passenger,...,4,185,107,67,41,28.0,14.0,3040,non-USA,Honda Accord
55,56,Mazda,MPV,Van,16.6,19.1,21.7,18,24,NaN,...,7,190,110,72,39,27.5,NaN,3735,non-USA,Mazda MPV
65,66,Nissan,Quest,Van,16.7,19.1,21.5,17,23,NaN,...,7,190,112,74,41,27.0,NaN,4100,non-USA,Nissan Quest
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,5,188,104,69,41,28.5,14.0,3200,non-USA,Nissan Maxima
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18,23,NaN,...,7,194,110,74,44,30.5,NaN,3715,USA,Oldsmobile Silhouette
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,19,28,Driver only,...,6,201,111,74,42,31.5,17.0,3470,USA,Oldsmobile Eighty-Eight
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,19,28,Driver & Passenger,...,4,196,101,75,43,25.0,13.0,3240,USA,Pontiac Firebird
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,NaN,...,5,195,108,72,41,28.5,16.0,3450,USA,Pontiac Grand_Prix
76,77,Pontiac,Bonneville,Large,19.4,24.4,29.4,19,28,Driver & Passenger,...,6,177,111,74,43,30.5,18.0,3495,USA,Pontiac Bonneville
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,5,179,102,67,37,27.0,14.0,3085,non-USA,Subaru Legacy
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,4,174,99,69,39,23.0,13.0,2950,non-USA,Toyota Celica
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,...,5,188,103,70,38,28.5,15.0,3030,non-USA,Toyota Camry
86,87,Toyota,Previa,Van,18.9,22.7,26.6,18,22,Driver only,...,7,187,113,71,41,35.0,NaN,3785,non-USA,Toyota Previa
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240

In [29]:
df.query('Price >= 17 & Price<=25')

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,19,28,Driver only,...,6,200,111,74,42,30.5,17.0,3470,USA,Buick LeSabre
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,6,216,116,78,45,30.5,21.0,4105,USA,Buick Roadmaster
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver & Passenger,...,6,203,113,74,40,31.0,15.0,3515,USA,Chrylser Concorde
25,26,Dodge,Caravan,Van,13.6,19.0,24.4,17,21,Driver only,...,7,175,112,72,42,26.5,NaN,3705,USA,Dodge Caravan
29,30,Eagle,Vision,Large,17.5,19.3,21.2,20,28,Driver & Passenger,...,6,202,113,74,40,30.0,15.0,3490,USA,Eagle Vision
35,36,Ford,Aerostar,Van,14.5,19.9,25.3,15,20,Driver only,...,7,176,119,72,45,30.0,NaN,3735,USA,Ford Aerostar
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,27.5,18.0,3325,USA,Ford Taurus
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,6,212,114,78,43,30.0,21.0,3950,USA,Ford Crown_Victoria
40,41,Honda,Prelude,Sporty,17.0,19.8,22.7,24,31,Driver & Passenger,...,4,175,100,70,39,23.5,8.0,2865,non-USA,Honda Prelude
42,43,Honda,Accord,Compact,13.8,17.5,21.2,24,31,Driver & Passenger,...,4,185,107,67,41,28.0,14.0,3040,non-USA,Honda Accord
55,56,Mazda,MPV,Van,16.6,19.1,21.7,18,24,NaN,...,7,190,110,72,39,27.5,NaN,3735,non-USA,Mazda MPV
65,66,Nissan,Quest,Van,16.7,19.1,21.5,17,23,NaN,...,7,190,112,74,41,27.0,NaN,4100,non-USA,Nissan Quest
66,67,Nissan,Maxima,Midsize,21.0,21.5,22.0,21,26,Driver only,...,5,188,104,69,41,28.5,14.0,3200,non-USA,Nissan Maxima
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18,23,NaN,...,7,194,110,74,44,30.5,NaN,3715,USA,Oldsmobile Silhouette
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,19,28,Driver only,...,6,201,111,74,42,31.5,17.0,3470,USA,Oldsmobile Eighty-Eight
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,19,28,Driver & Passenger,...,4,196,101,75,43,25.0,13.0,3240,USA,Pontiac Firebird
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,NaN,...,5,195,108,72,41,28.5,16.0,3450,USA,Pontiac Grand_Prix
76,77,Pontiac,Bonneville,Large,19.4,24.4,29.4,19,28,Driver & Passenger,...,6,177,111,74,43,30.5,18.0,3495,USA,Pontiac Bonneville
81,82,Subaru,Legacy,Compact,16.3,19.5,22.7,23,30,Driver only,...,5,179,102,67,37,27.0,14.0,3085,non-USA,Subaru Legacy
84,85,Toyota,Celica,Sporty,14.2,18.4,22.6,25,32,Driver only,...,4,174,99,69,39,23.0,13.0,2950,non-USA,Toyota Celica
85,86,Toyota,Camry,Midsize,15.2,18.2,21.2,22,29,Driver only,...,5,188,103,70,38,28.5,15.0,3030,non-USA,Toyota Camry
86,87,Toyota,Previa,Van,18.9,22.7,26.6,18,22,Driver only,...,7,187,113,71,41,35.0,NaN,3785,non-USA,Toyota Previa
88,89,Volkswagen,Eurovan,Van,16.6,19.7,22.7,17,21,NaN,...,7,187,115,72,38,34.0,NaN,3960,non-USA,Volkswagen Eurovan
89,90,Volkswagen,Passat,Compact,17.6,20.0,22.4,21,30,NaN,...,5,180,103,67,35,31.5,14.0,2985,non-USA,Volkswagen Passat
90,91,Volkswagen,Corrado,Sporty,22.9,23.3,23.7,18,25,NaN,...,4,159,97,66,36,26.0,15.0,2810,non-USA,Volkswagen Corrado
91,92,Volvo,240,Compact,21.8,22.7,23.5,21,28,Driver only,...,5,190,104,67,37,29.5,14.0,2985,non-USA,Volvo 240

In [30]:
# 3. Find out top 7 most fuel economic cars for highway
df.sort_values('MPG.highway' , ascending   = False).head(7)

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
38,39,Geo,Metro,Small,6.7,8.4,10.0,46,50,NaN,...,4,151,93,63,34,27.5,10.0,1695,non-USA,Geo Metro
41,42,Honda,Civic,Small,8.4,12.1,15.8,42,46,Driver only,...,4,173,103,67,36,28.0,12.0,2350,non-USA,Honda Civic
82,83,Suzuki,Swift,Small,7.3,8.6,10.0,39,43,NaN,...,4,161,93,63,34,27.5,10.0,1965,non-USA,Suzuki Swift
72,73,Pontiac,LeMans,Small,8.2,9.0,9.9,31,41,NaN,...,4,177,99,66,35,25.5,17.0,2350,USA,Pontiac LeMans
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,5,176,102,68,40,26.5,12.0,2495,USA,Saturn SL
83,84,Toyota,Tercel,Small,7.8,9.8,11.8,32,37,Driver only,...,5,162,94,65,36,24.0,11.0,2055,non-USA,Toyota Tercel
79,80,Subaru,Justy,Small,7.3,8.4,9.5,33,37,NaN,...,4,146,90,60,32,23.5,10.0,2045,non-USA,Subaru Justy

In [31]:
# 5. Find out top 7 most fuel economic cars for city, show results in sorted manner based on Horsepower.

df.sort_values(by  ='MPG.city'  , ascending  =  False).head(7)[['Manufacturer',	'Model' , 'MPG.city' , 'Horsepower']].sort_values('Horsepower')

   Manufacturer    Model  MPG.city  Horsepower
38          Geo    Metro        46          55
30         Ford  Festiva        31          63
82       Suzuki    Swift        39          70
79       Subaru    Justy        33          73
72      Pontiac   LeMans        31          74
83       Toyota   Tercel        32          82
41        Honda    Civic        42         102

In [32]:
df.Origin.unique()

array(['non-USA', 'USA'], dtype=object)

In [36]:
df.AirBags.value_counts()

AirBags
Driver only           42
Driver & Passenger    14
Name: count, dtype: int64

In [39]:
# 1. Find out Cars having mileage of more than 15 miles in city
df.query('`MPG.city`>15')[['Manufacturer' ,  'Model' , 'MPG.city']]

   Manufacturer    Model  MPG.city
0         Acura  Integra        25
1         Acura   Legend        18
2          Audi       90        20
3          Audi      100        19
4           BMW     535i        22
..          ...      ...       ...
88   Volkswagen  Eurovan        17
89   Volkswagen   Passat        21
90   Volkswagen  Corrado        18
91        Volvo      240        21
92        Volvo      850        20

[91 rows x 3 columns]

In [40]:
# 2. Find out Cars with US based origin¶
df.query('Origin=="USA"')

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
5,6,Buick,Century,Midsize,14.2,15.7,17.3,22,31,Driver only,...,6,189,105,69,41,28.0,16.0,2880,USA,Buick Century
6,7,Buick,LeSabre,Large,19.9,20.8,21.7,19,28,Driver only,...,6,200,111,74,42,30.5,17.0,3470,USA,Buick LeSabre
7,8,Buick,Roadmaster,Large,22.6,23.7,24.9,16,25,Driver only,...,6,216,116,78,45,30.5,21.0,4105,USA,Buick Roadmaster
8,9,Buick,Riviera,Midsize,26.3,26.3,26.3,19,27,Driver only,...,5,198,108,73,41,26.5,14.0,3495,USA,Buick Riviera
9,10,Cadillac,DeVille,Large,33.0,34.7,36.3,16,25,Driver only,...,6,206,114,73,43,35.0,18.0,3620,USA,Cadillac DeVille
10,11,Cadillac,Seville,Midsize,37.5,40.1,42.7,16,25,Driver & Passenger,...,5,204,111,74,44,31.0,14.0,3935,USA,Cadillac Seville
11,12,Chevrolet,Cavalier,Compact,8.5,13.4,18.3,25,36,NaN,...,5,182,101,66,38,25.0,13.0,2490,USA,Chevrolet Cavalier
12,13,Chevrolet,Corsica,Compact,11.4,11.4,11.4,25,34,Driver only,...,5,184,103,68,39,26.0,14.0,2785,USA,Chevrolet Corsica
13,14,Chevrolet,Camaro,Sporty,13.4,15.1,16.8,19,28,Driver & Passenger,...,4,193,101,74,43,25.0,13.0,3240,USA,Chevrolet Camaro
14,15,Chevrolet,Lumina,Midsize,13.4,15.9,18.4,21,29,NaN,...,6,198,108,71,40,28.5,16.0,3195,USA,Chevrolet Lumina
15,16,Chevrolet,Lumina_APV,Van,14.7,16.3,18.0,18,23,NaN,...,7,178,110,74,44,30.5,NaN,3715,USA,Chevrolet Lumina_APV
16,17,Chevrolet,Astro,Van,14.7,16.6,18.6,15,20,NaN,...,8,194,111,78,42,33.5,NaN,4025,USA,Chevrolet Astro
17,18,Chevrolet,Caprice,Large,18.0,18.8,19.6,17,26,Driver only,...,6,214,116,77,42,29.5,20.0,3910,USA,Chevrolet Caprice
18,19,Chevrolet,Corvette,Sporty,34.6,38.0,41.5,17,25,Driver only,...,2,179,96,74,43,NaN,NaN,3380,USA,Chevrolet Corvette
19,20,Chrylser,Concorde,Large,18.4,18.4,18.4,20,28,Driver & Passenger,...,6,203,113,74,40,31.0,15.0,3515,USA,Chrylser Concorde
20,21,Chrysler,LeBaron,Compact,14.5,15.8,17.1,23,28,Driver & Passenger,...,6,183,104,68,41,30.5,14.0,3085,USA,Chrysler LeBaron
21,22,Chrysler,Imperial,Large,29.5,29.5,29.5,20,26,NaN,...,6,203,110,69,44,36.0,17.0,3570,USA,Chrysler Imperial
22,23,Dodge,Colt,Small,7.9,9.2,10.6,29,33,NaN,...,5,174,98,66,32,26.5,11.0,2270,USA,Dodge Colt
23,24,Dodge,Shadow,Small,8.4,11.3,14.2,23,29,Driver only,...,5,172,97,67,38,26.5,13.0,2670,USA,Dodge Shadow
24,25,Dodge,Spirit,Compact,11.9,13.3,14.7,22,27,Driver only,...,6,181,104,68,39,30.5,14.0,2970,USA,Dodge Spirit
25,26,Dodge,Caravan,Van,13.6,19.0,24.4,17,21,Driver only,...,7,175,112,72,42,26.5,NaN,3705,USA,Dodge Caravan
26,27,Dodge,Dynasty,Midsize,14.8,15.6,16.4,21,27,Driver only,...,6,192,105,69,42,30.5,16.0,3080,USA,Dodge Dynasty
27,28,Dodge,Stealth,Sporty,18.5,25.8,33.1,18,24,Driver only,...,4,180,97,72,40,20.0,11.0,3805,USA,Dodge Stealth
28,29,Eagle,Summit,Small,7.9,12.2,16.5,29,33,NaN,...,5,174,98,66,36,26.5,11.0,2295,USA,Eagle Summit
29,30,Eagle,Vision,Large,17.5,19.3,21.2,20,28,Driver & Passenger,...,6,202,113,74,40,30.0,15.0,3490,USA,Eagle Vision
30,31,Ford,Festiva,Small,6.9,7.4,7.9,31,33,NaN,...,4,141,90,63,33,26.0,12.0,1845,USA,Ford Festiva
31,32,Ford,Escort,Small,8.4,10.1,11.9,23,30,NaN,...,5,171,98,67,36,28.0,12.0,2530,USA,Ford Escort
32,33,Ford,Tempo,Compact,10.4,11.3,12.2,22,27,NaN,...,5,177,100,68,39,27.5,13.0,2690,USA,Ford Tempo
33,34,Ford,Mustang,Sporty,10.8,15.9,21.0,22,29,Driver only,...,4,180,101,68,40,24.0,12.0,2850,USA,Ford Mustang
34,35,Ford,Probe,Sporty,12.8,14.0,15.2,24,30,Driver only,...,4,179,103,70,38,23.0,18.0,2710,USA,Ford Probe
35,36,Ford,Aerostar,Van,14.5,19.9,25.3,15,20,Driver only,...,7,176,119,72,45,30.0,NaN,3735,USA,Ford Aerostar
36,37,Ford,Taurus,Midsize,15.6,20.2,24.8,21,30,Driver only,...,5,192,106,71,40,27.5,18.0,3325,USA,Ford Taurus
37,38,Ford,Crown_Victoria,Large,20.1,20.9,21.7,18,26,Driver only,...,6,212,114,78,43,30.0,21.0,3950,USA,Ford Crown_Victoria
50,51,Lincoln,Continental,Midsize,33.3,34.3,35.3,17,26,Driver & Passenger,...,6,205,109,73,42,30.0,19.0,3695,USA,Lincoln Continental
51,52,Lincoln,Town_Car,Large,34.4,36.1,37.8,18,26,NaN,...,6,219,117,77,45,31.5,22.0,4055,USA,Lincoln Town_Car
59,60,Mercury,Capri,Sporty,13.3,14.1,15.0,23,26,Driver only,...,4,166,95,65,36,19.0,6.0,2450,USA,Mercury Capri
60,61,Mercury,Cougar,Midsize,14.9,14.9,14.9,19,26,NaN,...,5,199,113,73,38,28.0,15.0,3610,USA,Mercury Cougar
67,68,Oldsmobile,Achieva,Compact,13.0,13.5,14.0,24,31,NaN,...,5,188,103,67,39,28.0,14.0,2910,USA,Oldsmobile Achieva
68,69,Oldsmobile,Cutlass_Ciera,Midsize,14.2,16.3,18.4,23,31,Driver only,...,5,190,105,70,42,28.0,16.0,2890,USA,Oldsmobile Cutlass_Ciera
69,70,Oldsmobile,Silhouette,Van,19.5,19.5,19.5,18,23,NaN,...,7,194,110,74,44,30.5,NaN,3715,USA,Oldsmobile Silhouette
70,71,Oldsmobile,Eighty-Eight,Large,19.5,20.7,21.9,19,28,Driver only,...,6,201,111,74,42,31.5,17.0,3470,USA,Oldsmobile Eighty-Eight
71,72,Plymouth,Laser,Sporty,11.4,14.4,17.4,23,30,NaN,...,4,173,97,67,39,24.5,8.0,2640,USA,Plymouth Laser
72,73,Pontiac,LeMans,Small,8.2,9.0,9.9,31,41,NaN,...,4,177,99,66,35,25.5,17.0,2350,USA,Pontiac LeMans
73,74,Pontiac,Sunbird,Compact,9.4,11.1,12.8,23,31,NaN,...,5,181,101,66,39,25.0,13.0,2575,USA,Pontiac Sunbird
74,75,Pontiac,Firebird,Sporty,14.0,17.7,21.4,19,28,Driver & Passenger,...,4,196,101,75,43,25.0,13.0,3240,USA,Pontiac Firebird
75,76,Pontiac,Grand_Prix,Midsize,15.4,18.5,21.6,19,27,NaN,...,5,195,108,72,41,28.5,16.0,3450,USA,Pontiac Grand_Prix
76,77,Pontiac,Bonneville,Large,19.4,24.4,29.4,19,28,Driver & Passenger,...,6,177,111,74,43,30.5,18.0,3495,USA,Pontiac Bonneville
78,79,Saturn,SL,Small,9.2,11.1,12.9,28,38,Driver only,...,5,176,102,68,40,26.5,12.0,2495,USA,Saturn SL

In [44]:
# 3. Find out Cars with no airbags and which are compact in type, from the output retrieve only Model, Mileage in city, Type, Airbags
df.query('AirBags=="None" & \
Type== "Compact"' )[['Model', 'MPG.city', 'Type', 'AirBags']]

Empty DataFrame
Columns: [Model, MPG.city, Type, AirBags]
Index: []

In [42]:

# 4. Find out cars with Mileage in city more than 15 which are compact in type.
df.query('`MPG.city`>15 \
 & Type== "Compact"' )\
  [['Model', 'MPG.city', 'Type', 'AirBags']]

       Model  MPG.city     Type             AirBags
2         90        20  Compact         Driver only
11  Cavalier        25  Compact                 NaN
12   Corsica        25  Compact         Driver only
20   LeBaron        23  Compact  Driver & Passenger
24    Spirit        22  Compact         Driver only
32     Tempo        22  Compact                 NaN
42    Accord        24  Compact  Driver & Passenger
54       626        26  Compact         Driver only
57      190E        20  Compact         Driver only
64    Altima        24  Compact         Driver only
67   Achieva        24  Compact                 NaN
73   Sunbird        23  Compact                 NaN
77       900        20  Compact         Driver only
81    Legacy        23  Compact         Driver only
89    Passat        21  Compact                 NaN
91       240        21  Compact         Driver only